version: "3.8"
services:
  db:
    image: postgres:17.5-alpine3.22
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_manage
      POSTGRES_USER: trung_db
      POSTGRES_PASSWORD: trung2001@
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  db_data:
